### ISSUE TITLE
doesnt work in in windows

### ISSUE THREAD

**Issue by Zhangsun321** [schwifty42069/piptv#1]
https://i.imgur.com/aoqVsJc.png

**Comment by schwifty42069** [comment]
Do you have the requests module installed? Did you pip install the requirements.txt?

I'm sorry I haven't had the chance to test it in a windows environment yet, I will get on that tomorrow.

**Comment by Zhangsun321** [comment]
i know zip bout python scripts...  i just copied it to my cmd prompt...
   lemme do some research on those two commands youve given..    you 
could do a step by step 'how to guide' for windows.....   time for me to 
learn something...
------ Original Message ------

**Comment by schwifty42069** [comment]
Yeah I will have a step by step doc up tomorrow. It is definitely a simple fix though, you're just missing the required dependencies. You can look up how to install pip in the meantime though. I will leave this issue open until I get the docs up.

**Comment by schwifty42069** [comment]
I am going to close this, as it seems like it's just that you're missing dependencies and I will be adding step by step docs today.
