### ISSUE TITLE
OSError: [WinError 126] The specified module could not be found

### ISSUE THREAD

**Issue by SpookyOugiofCute** [schwifty42069/piptv#12]
Attempting to execute the code results in the following:

```
PS C:\> python piptv.py 
Traceback (most recent call last):   
    File "piptv.py", line 4, in <module>     
        import vlc   
    File "C:\Users\xxx_000\AppData\Local\Programs\Python\Python37\lib\site-packages\vlc.py", line 207, in <module>     
        dll, plugin_path  = find_lib()   
    File "C:\Users\xxx_000\AppData\Local\Programs\Python\Python37\lib\site-packages\vlc.py", line 167, in find_lib     
        dll = ctypes.CDLL(libname)   
       File "C:\Users\xxx_000\AppData\Local\Programs\Python\Python37\lib\ctypes\__init__.py", line 364, in __init__     
        self._handle = _dlopen(self._name, mode) 
OSError: [WinError 126] The specified module could not be found
```

The following has been attempted:

1. Restart and attempting to go through the steps again
2. Download Python from the official site 3. Move the .py file to different directories
3. Download the file from https://github.com/schwifty42069/piptv/raw/master/piptv.py along with the original Github. 
4. Updated my Net Framework
5. Updated VLC to the newest version

**Comment by schwifty42069** [comment]
Alright, let's see what we can do. Is this windows 10?

**Comment by SpookyOugiofCute** [comment]
It is indeed Windows 10

**Comment by schwifty42069** [comment]
Can you try following [this guide](https://github.com/schwifty42069/piptv/blob/master/doc/windows.md)

**Comment by schwifty42069** [comment]
If I remember correctly, it's a VLC issue that can be resolved if you follow that doc to the T

**Comment by schwifty42069** [comment]
Did you forget to install the dependencies?

**Comment by SpookyOugiofCute** [comment]
Not that I'm aware of, I've followed that doc when I first installed, just running through the steps again

**Comment by schwifty42069** [comment]
Alright, let me know what happens after you follow that doc

**Comment by SpookyOugiofCute** [comment]
Everything was running smoothly until 

```
PS C:\WINDOWS\system32> choco install -y python3
Chocolatey v0.10.15
Installing the following packages:
python3
By installing you accept licenses for the packages.
Progress: Downloading python3 3.7.4... 100%

python3 v3.7.4 [Approved]
python3 package files install completed. Performing other installation steps.
Installing 64-bit python3...
WARNING: Generic MSI Error. This is a local environment error, not an issue with a package or the MSI itself - it could mean a pending reboot is necessary prior to install or something else (like the same version is already installed). Please see MSI log if available. If not, try again adding '--install-arguments="'/l*v c:\python3_msi_install.log'"'. Then search the MSI Log for "Return Value 3" and look above that for the error.
ERROR: Running ["C:\ProgramData\chocolatey\lib\python3\tools\python-3.7.4-amd64.exe" /quiet InstallAllUsers=1 PrependPath=1 TargetDir="C:\Python37" ] was not successful. Exit code was '1603'. Exit code indicates the following: Generic MSI Error. This is a local environment error, not an issue with a package or the MSI itself - it could mean a pending reboot is necessary prior to install or something else (like the same version is already installed). Please see MSI log if available. If not, try again adding '--install-arguments="'/l*v c:\python3_msi_install.log'"'. Then search the MSI Log for "Return Value 3" and look above that for the error..
The install of python3 was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\python3\tools\chocolateyInstall.ps1'.
 See log for details.

Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - python3 (exited 1603) - Error while running 'C:\ProgramData\chocolatey\lib\python3\tools\chocolateyInstall.ps1'.
 See log for details.
```

I presume that this is because I had python previously installed?

**Comment by schwifty42069** [comment]
Most likely. If you have a working installation of python3 you should be good. Try to type python --version in a cmd and see if it spits the version number back

**Comment by SpookyOugiofCute** [comment]
3.7.4

**Comment by schwifty42069** [comment]
Perfect. Also, redo the installation of the dependencies with pip install -r requirements.txt in the directory you have piptv

**Comment by SpookyOugiofCute** [comment]
Installed all the pip's, just going to run python piptv.py now and see if it errors out again

**Comment by SpookyOugiofCute** [comment]
Error again, I'm going to attach a screencap of the powershell for you
![Capture](https://user-images.githubusercontent.com/55640394/65380607-deaee400-dcac-11e9-90b7-2411d6070436.JPG)

**Comment by schwifty42069** [comment]
Your pip install for python is incorrect.

Try pip install python-vlc

instead of pip install python_vlc

**Comment by SpookyOugiofCute** [comment]
```
PS C:\WINDOWS\system32> pip install python-vlc
Requirement already satisfied: python-vlc in c:\users\natha_000\appdata\local\programs\python\python37\lib\site-packages (3.0.7110)
```

**Comment by schwifty42069** [comment]
Damn it -_-  You're still getting that exception? WinError 126?

**Comment by SpookyOugiofCute** [comment]
Yep. I'll run through everything yet again though, just as a precaution.

**Comment by schwifty42069** [comment]
Oh shit, in that screenshot it looks like you're trying to run it from system32. Are you in the directory where piptv is? Type dir and see what it says

**Comment by SpookyOugiofCute** [comment]
I switched to the directory where Piptv is after step 5, like the instructions said. But I'll try again from that directory

**Comment by schwifty42069** [comment]
Sorry about this. The python bindings for VLC are a huge pain in the ass

**Comment by SpookyOugiofCute** [comment]
Not a problem, sorry you have to go through all this with me

**Comment by schwifty42069** [comment]
If all else fails, I wrote another script that generates an m3u with all of the channels to be used with plex/kodi. I will walk you through that one if we can't get this to work. It uses the same scraper logic and formats a pretty m3u, but doesn't use the vlc python bindings, so you can just manually play the m3u it generates in vlc

**Comment by SpookyOugiofCute** [comment]
126 error again, and even ran it from the folder with all the files in the Github, I'll try that other file you mentioned. Not sure what the hell is the matter. Might be missing some file somewhere in my OS

**Comment by schwifty42069** [comment]
Yeah I saw this error with another person but following the aforementioned doc resolved it. Go ahead and clone the piptv-plex repo and I will walk you through it.

**Comment by schwifty42069** [comment]
There is a config folder in the repo that contains a config.properties file. Change the dir= key to the directory you want the m3u to be written to, including its name.

For example:

dir=C:\Users\Me\m3u_folder\piptv.m3u

**Comment by schwifty42069** [comment]
Then you can just run the script and wait, it takes about a minute and a half and is quiet (no output in the console) You should already have the dependencies you need

**Comment by SpookyOugiofCute** [comment]
I'm running Plex off of an external server, does this look right?

dir=F:\Movies\TV\Live TV/m3u/piptv.m3u

**Comment by schwifty42069** [comment]
Yeah, I'm not sure it will work correctly in plex yet. A buddy and I are working on documenting the process to make it work like butter, but you can try it. If it doesn't work in plex, it will most definitely work in vlc.

**Comment by schwifty42069** [comment]
Whoa you have back and forward slashes in your directory though. Is that intentional? I am an all Linux guy so Windows isn't my strong suite haha

**Comment by SpookyOugiofCute** [comment]
I don't think it is, but it works, so I'm not going to mess around with it lmao

**Comment by SpookyOugiofCute** [comment]
just running it now in powershell

**Comment by schwifty42069** [comment]
Alright let me know what happens.

**Comment by SpookyOugiofCute** [comment]
Still waiting, oddly enough

```
PS C:\Users\natha_000> cd F:\piptv-plex-master
PS F:\piptv-plex-master> python piptv-plex.py
```

**Comment by SpookyOugiofCute** [comment]
I believe that's what I'm supposed to do

**Comment by schwifty42069** [comment]
Yeah it takes a bit, it has to send, process, and parse 82 requests, and then assemble all the data and write it to a file. The first part takes a bit.

**Comment by SpookyOugiofCute** [comment]
```
PS F:\piptv-plex-master> python piptv-plex.py
Traceback (most recent call last):
  File "piptv-plex.py", line 97, in <module>
    main()
  File "piptv-plex.py", line 92, in main
    mw.initialize_m3u_file()
  File "piptv-plex.py", line 73, in initialize_m3u_file
    with open(write_dir, "w") as writer:
FileNotFoundError: [Errno 2] No such file or directory: 'F:\\Movies\\TV\\Live TV/m3u/piptv.m3u'
```

**Comment by schwifty42069** [comment]
Okay, so your goofy path is wrong.

**Comment by SpookyOugiofCute** [comment]
I'll throw it on my desktop then, my apologies

**Comment by schwifty42069** [comment]
Just try to write it to the directory the script is in

**Comment by schwifty42069** [comment]
so it would be:

dir=piptv.m3u

**Comment by schwifty42069** [comment]
haha no worries man. I just want people to use it and enjoy it. I slapped these together real quick as soon as I figured out the scraping logic

**Comment by SpookyOugiofCute** [comment]
Should work this time lol. Changed the directory in the config file, and ran it with no weird slashes

```
PS C:\WINDOWS\system32> cd C:\Users\natha_000\Desktop\piptv-plex-master
PS C:\Users\natha_000\Desktop\piptv-plex-master> python piptv-plex.py
```

**Comment by schwifty42069** [comment]
Alrighty, fingers crossed. I would test it in vlc first after it completes. Then see if you can get plex to run it. We will have a well documented process soon for plex. Also, the auth tokens only last 6 hours, so you will need to rerun it before then. We are gonna have a guide to setup a cron job to automate it.

**Comment by schwifty42069** [comment]
Also, I think I remember the source of the issues of the regular piptv script, I think it's an architecture mismatch. So you probably have 64bit Python and 32bit VLC or vice versa.

**Comment by SpookyOugiofCute** [comment]
I can check that, I presume that I installed 64 python and 64 VLC, as I'm on a 64 bit OS, but let me check that for you

**Comment by schwifty42069** [comment]
Freaking python vlc bindings are such a pain -_-

At least there's the other script, which I think I am going to integrate with the original

**Comment by SpookyOugiofCute** [comment]
I can believe it. I have 64 bit Python, and am doing a fresh install of VLC, I'll see if that clears up the issue, once this Plex one is done running.

**Comment by SpookyOugiofCute** [comment]
Aha, so it was an issue with VLC's version. 
![Capture](https://user-images.githubusercontent.com/55640394/65381020-e3c46100-dcb5-11e9-8784-f476b5a2e37a.JPG)

**Comment by schwifty42069** [comment]
Also, I don't know if you're a football fan, but I am posting HLS links for all the games tomorrow, and I am working on a script to aggregate all the streams from r/nflstreams for a one touch stream of every game. If you haven't already, you should sub to r/hlsvillage

**Comment by schwifty42069** [comment]
Nice! Hell yeahhhh

Make sure the other script works too

**Comment by schwifty42069** [comment]
I think the colors will correct themselves after you tune to a channel. Something with windows 10 vtx100 virtualization makes the color codes whacky at first.

**Comment by SpookyOugiofCute** [comment]
So now you know, if you have that error again with someone else, to try checking VLC. I will also try the Plex version as well. I'm not really a football fan aside from the Superbowl lol.

**Comment by schwifty42069** [comment]
Oh so you're a patriots fan like me then? ;D hahaha

Yeah let me know if that works, and if all is well I will close this up

**Comment by schwifty42069** [comment]
I knew it was a vlc issue I just couldn't remember the specifics. I have been putting out fires all over today my brain is scrambled haha

**Comment by SpookyOugiofCute** [comment]
Haha, I don't have a favorite team per se, I just pick one at random and cheer for them. I have an m3u file now, I presume I just throw it in VLC?

**Comment by schwifty42069** [comment]
Yes sirrrr. Make sure it works.

**Comment by SpookyOugiofCute** [comment]
Yep, I've got football, not sure how to change the channel

**Comment by schwifty42069** [comment]
click the little list button on the bottom of the player, you will see all the channels

**Comment by SpookyOugiofCute** [comment]
Yep, tried 4 channels at random, they all seem to work. Thank you so much for taking the time to help out sir/madam.

**Comment by schwifty42069** [comment]
I'm a sir, you're so welcome! Just glad it's working. Have a great night!
