### ISSUE TITLE
Keep getting the invalid syntax on windows 10

### ISSUE THREAD

**Issue by mattbattherat** [schwifty42069/piptv#13]
I've downloaded and run python 3 and vic it just wont work.
And I did the step with powershell

**Comment by schwifty42069** [comment]
Alright, you're gonna have to give me more than that lol. What version of python are you running, type python --version in powershell. Also, send me a screen shot, or copy and paste the stack trace for the entire error.

**Comment by schwifty42069** [comment]
By "the step with powershell" do you mean you installed the dependencies from the requirements.txt?

**Comment by mattbattherat** [comment]
I just realised I'm to illiterate on the subject to give you a sufficient answer sorry for wasting your time

**Comment by schwifty42069** [comment]
I promise we could get it running. Try to run the script, and then take a screenshot or copy and paste the error you get in here for me.

**Comment by mattbattherat** [comment]
I run it and it opens for a quick second then disappears

**Comment by schwifty42069** [comment]
How are you trying to open it? python piptv.py?

Send me screenshots, 

also, in a powershell, try typing 

pip install requests [hit enter] 
pip install bs4 [hit enter] 
pip install python-vlc[hit enter]

And tell me what happens

**Comment by mattbattherat** [comment]
![Annotation 2019-09-24 184958](https://user-images.githubusercontent.com/42031045/65536999-54f55580-defc-11e9-9869-5db2142e57cd.png)

**Comment by schwifty42069** [comment]
okay type python --version and show me what it says

If you had the newest python installed, pip would be bundled with it

**Comment by mattbattherat** [comment]
i went straight to the website  and installed the first option 
![Annotation 2019-09-24 184958](https://user-images.githubusercontent.com/42031045/65537451-2461eb80-defd-11e9-9f2c-e46968ad35fb.png)

**Comment by schwifty42069** [comment]
Type python --version and show me what it says.

Try running 

python -m pip install requests 

instead of just pip by itself. The reason its not working is because you never installed any of the dependencies per the documentation. You can find a step by step in this repository [here](https://github.com/schwifty42069/piptv/blob/master/doc/windows.md). I will try to help you out, though.

**Comment by schwifty42069** [comment]
When you installed python, did you click the check box at the bottom of the installed that said "Add python to path" ? Because if you didn't, and you actually have python 3,7 installed, I will have to walk you through adding it to your path environment variable.

**Comment by mattbattherat** [comment]
Is it meant to come in a rar or exe?

**Comment by schwifty42069** [comment]
Python? Pretty sure it's just an exe if you download the installer off their site.

**Comment by schwifty42069** [comment]
I will leave this open until the end of the day, if you come back with some more info, I will continue to help. but I will be closing this by the end of the day if not since it appears you didn't install any dependencies
