### ISSUE TITLE
Stopped working today, anyone else?

### ISSUE THREAD

**Issue by tobedev** [schwifty42069/piptv#14]
Was working fine yesterday and earlier today, then it stopped working.
Here’s what I get when I try to tune in:

Trying to tune to tlc...

Traceback (most recent call last):
  File "piptv.py", line 180, in <module>
    main()
  File "piptv.py", line 176, in main
    stb.tune_to_channel(command)
  File "piptv.py", line 126, in tune_to_channel
    self.player.set_mrl(hotlink)
  File "/home/still/.local/lib/python3.5/site-packages/vlc.py", line 3331, in set_mrl
    m = self.get_instance().media_new(mrl, *options)
  File "/home/still/.local/lib/python3.5/site-packages/vlc.py", line 1908, in media_new
    if ':' in mrl and mrl.index(':') > 1:
TypeError: argument of type 'NoneType' is not iterable

**Comment by schwifty42069** [comment]
When did you download it last?

**Comment by schwifty42069** [comment]
Still works for me on a fresh clone. Let me know when you're available and I will give you instructions to troubleshoot

**Comment by schwifty42069** [comment]
When you're back, do the following for me:

open a python shell

type the following:

```
import requests
import pprint
pprint.pprint(requests.get("http://ustvgo.tv/nfl-network-live-free").text)
```

Paste the output of that here for me. I have a feeling they may be blocking your IP address range from cloudflare. It happened to another person. If they're blocking your IP, it will explicitly say so in the response. The code above will show us what data is being returned from a request to the site. If the output is huge, and doesn't say anything about blocking your IP, we will move on and try something else. Thank you!

**Comment by tobedev** [comment]
@schwifty42069  
Sorry for not getting back to you earlier.
I re-clonned the repo. today right after it stopped working, just in case I missed with the script or something.
I tried the commands you provided, and looks like I'm getting a valid response, as in a wall of HTML code, and nothing indicates that am being blocked, plus I can access the website and stream off it just fine.

Let me know what else I should try.
Thanks!

**Comment by schwifty42069** [comment]
Hmmm. Alright, let's try and narrow down on where the issue is. 

in a python shell try this for me

```
import requests
from bs4 import BeautifulSoup as Soup

bsoup = Soup(requests.get("http://ustvgo.tv/nfl-network-live-free").text, 'html.parser')
for s in bsoup.findAll("script"):
    if "player.setup" in str(s):
        print(s.next_element.split(" file: ")[1].split(',')[0].strip("\'"))
```

This is basically just the core scraping logic from the script, if we get back a hotlink, then the problem is likely the python bindings for vlc, which have proven to be a bit of a pain

**Comment by schwifty42069** [comment]
Looks like they added DDOS protection through cloudflare, which is defeating the script. I am working on a way to patch it... Really disappointing

**Comment by tobedev** [comment]
Yesterday it refused to work at all throwing the above mentioned error, I even suspected the VM itself and gave it a try on a remote DO. VPS of mine. Well, same exact thing.

Today it worked out of the blue and still working to this second! So weird, as like I mentioned before, I'm not blocked by CloudFlare or anything.

And yea, I wasn't trying to stream through VLC (was just trying to get/print the streaming URL), and even tried your 'pmg' script, and same thing, wasn't working yesterday, but started working today.

If you need a hand testing/debugging anything, just let know. I have Windows, Mac, and Linux machines at hand.

**Comment by schwifty42069** [comment]
I just wrote a patch. it adds a dependency cfscrape, you will also need to have nodejs installed, but I just tested it and it worked for me, give it a try for me?

**Comment by schwifty42069** [comment]
Wait whattt? Haha that is so weird. Well it's patched for the future, you can use either version, I am about to patch pmg too

**Comment by schwifty42069** [comment]
Also, MacOS seems to be a pain in the ass with the vlc python bindings(hence the only other open issue), I have played around with it in a VM but have only gotten sound to work. I would love some help debugging for MacOS. I will leave this issue open for you to respond, then I will close. Will need some real contact info from you haha

**Comment by tobedev** [comment]
Got the same issue today with the exact same error I posted earlier, with both the old script and the new one, and in both cases just to eliminate the VLC side of things I just comment out 'self.run()' line, and add 'print(hotlink)' in the 'tune_to_channel' function.

Let me know how to proceed with this issue, and also with debugging on MacOS.
You can reach me on mhany (a t) stillcode.com
