### ISSUE TITLE
Win10 issue - TypeError: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by slower01** [schwifty42069/piptv#16]
When trying to tune to any stream, I get the following error:
![image](https://user-images.githubusercontent.com/29824721/66704532-060c3600-ecda-11e9-9ce8-c4f7d7e556cc.png)

System:
![image](https://user-images.githubusercontent.com/29824721/66704527-ef65df00-ecd9-11e9-8bd0-682cab043fb3.png)

**Comment by schwifty42069** [comment]
Unfortunately, the site that's being scraped has added cloudflare anti-bot protection, which has defeated the script in it's current form. I have developed a patch for it's sister script [pmg](https://github.com/schwifty42069/pmg), I just haven't had the time to refactor this to use it. You can use pmg in the meantime, though!
