### ISSUE TITLE
Win 10 issue Import VLC

### ISSUE THREAD

**Issue by DarkNightHawk** [schwifty42069/piptv#18]
After trying this 

> Prepare for a longer explanation, I will walk you through everything, if not stated otherwise commands should be ran in Powershell, as an admin.
> 
>     First and foremost, download VLC and install it, if you don't already have it
>     Link: https://www.videolan.org/vlc/index.html
>     Edit: Make sure you download the 64-bit version (thank you for mentioning it u/Hairless_Human)
> 
>     Next, we will need Python, the easiest way is through powershell with Chocolatey to install Chocolatey copy Set-ExecutionPolicy Bypass -Scope Process -Force; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1')) into powershell and wait for it to be completed.
> 
>     Next we will need Python itself, copy choco install -y python3 and wait for it to be completed, you may have to sign out & in out of Windows after this.
> 
>     Now write python --version to make sure that it is actually installed (if not and you haven't already logged out and in, do it, it should fix it)
> 
>     Now we will need the requirements, the crude way of getting them is with pip, copy these commands one-by-one and wait for them to be completed:
>     python -m pip install requests
>     python -m pip install beautifulsoup4
>     python -m pip install python_vlc
> 
>     Now, if you don't already have the piptv.py file then you can do so by right-clicking on this link and choosing "Save link as..." save it to your desired location.
> 
>     Now cd over to that location with Powershell, once you are in the folder do python piptv.py (or python yourfilename.py ) it should start the program, albeit with funky coloring codes, they should be fixed after tuning to a channel and stopping the playback
>     Edit: As noted by u/sortbycontroversial2 I didn't exactly mention what cd it means change directory so by cd over to the location I basically mean to note where you saved the python file and write cd "THEDIRECTORY WHERE IT IS" so if you saved it in your C: drive you would write cd C:\

On my Windows 10 and on an fresh Win10 WM the same error shows up. I´m using Python 3.8 and tried VLC 64 Bit 3.0.7, 3.0.8 and the Windows Store Version.

**Comment by DarkNightHawk** [comment]
https://youtu.be/9aJA8lBo7fI?t=1494 Tried with a new VM. same result

**Comment by schwifty42069** [comment]
Try using it's sister script [pmg](https://github.com/schwifty42069/pmg)

It generates an m3u with all of the channels that you can manually load in VLC and not have to deal with the annoying Python bindings for VLC. It has essentially replaced this script.

You can install it by doing the following in a terminal:

```
python -m pip install piptv_pmg
```

I'll leave this open so you have a chance to reply.

**Comment by schwifty42069** [comment]
Closing
