### ISSUE TITLE
Cannot tune on MacOS (Catalina)

### ISSUE THREAD

**Issue by yellowstring** [schwifty42069/piptv#19]
Whenever I try to tune to a channel I get this error:
">>" hbo  

Trying to tune to hbo...

Traceback (most recent call last):
  File "piptv.py", line 181, in <module>
    main()
  File "piptv.py", line 177, in main
    stb.tune_to_channel(command)
  File "piptv.py", line 127, in tune_to_channel
    self.player.set_mrl(hotlink)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/vlc.py", line 3331, in set_mrl
    m = self.get_instance().media_new(mrl, *options)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/vlc.py", line 1908, in media_new
    if ':' in mrl and mrl.index(':') > 1:
TypeError: argument of type 'NoneType' is not iterable

Do you know what the cause of this issue is? And on top of that do you know how to fix it?

**Comment by schwifty42069** [comment]
Use it's sister script [pmg](https://github.com/schwifty42069/pmg)

It has replaced this script, as the site it scrapes has added anti-bot protection, so I re-engineered the script into pmg (Piptv m3u Generator)

It generates an m3u with all of the channels that you can manually load in VLC and not have to deal with the annoying Python bindings for VLC. 

You can install it by doing the following in a terminal:
```
python -m pip install piptv_pmg
````

I'll leave this open so you have a chance to reply.

**Comment by schwifty42069** [comment]
Closing due to no reply, @yellowstring  if you have a problem using pmg, let me know.
