### ISSUE TITLE
Error whilst getting hls hotlink (Line 103- List index out of range)

### ISSUE THREAD

**Issue by tobynott80** [schwifty42069/piptv#2]
Runs fine until I try to tune.

![error](https://i.imgur.com/aNDxKmX.jpg)

I'm running windows but that doesn't seem to be the issue. 

Cheers

**Comment by ZoleeHUN** [comment]
Hey!
I'm also on Windows, when I try to tune to usa network (or any channel for that matter) it works correctly.
I would make sure that all requirements are installed correctly.

For a crude method try running:
`python -m pip install requests
 python -m pip install beautifulsoup4
 python -m pip install python_vlc`
in powershell.

**Comment by schwifty42069** [comment]
I will be running some tests today in a windows environments whilst I am updating the docs, so give me a little while and I will get back to you. This seems to be a common problem.

**Comment by schwifty42069** [comment]
writing a patch for this, looks like in windows the script element it pulls the link out of is in position 14 of the list instead of 15.

**Comment by schwifty42069** [comment]
Just posted a quick and dirty patch, will do a full refactor to remove the need for the list of elements all together, but should be okay for now, closing this.
