### ISSUE TITLE
something happened to it since last night

### ISSUE THREAD

**Issue by bashb** [schwifty42069/piptv#20]
something happened to it since last night

**Comment by schwifty42069** [comment]
This script doesn't work anymore, but it's sister script [pmg](https://github.com/schwifty42069/pmg) does, I re-engineered piptv to build it, and patched it today! You can install it with pip using the following command:

**For Windows**

```
python -m pip install piptv_pmg
``` 

**For Ubuntu/Debian**

```
python3 -m pip install piptv_pmg
```

Use it instead! Docs are in the repo, it's really simple.
