### ISSUE TITLE
everything looks right?

### ISSUE THREAD

**Issue by Zhangsun321** [schwifty42069/piptv#9]
https://i.imgur.com/Eu1fjMj.png

I then paste 

pip install -r requirements.txt

https://i.imgur.com/gN6GuVY.png is what i get

NOW.. when I drag the requirements.txt file into the shell...

https://i.imgur.com/eF2ZA4y.png

ok... ive tried pasting both of the commands.. and also tried draging both of the .txt and .py file into the shell.. nothing..  I dragged it from my download directory..  and i copied the files to 'open file location'  for my python 64.. i re installed.. allowing PATH and installing for all users..

I am at a loss for what I can try next.. TY

**Comment by schwifty42069** [comment]
Judging by that picture you're trying to run pip from inside a python shell. Try running it just in a command prompt, not in a python shell.

**Comment by schwifty42069** [comment]
Closing this, if you still have an issue after successfully running pip, open a new issue. Thank you!
